#!/usr/bin/python
#!python
import glob
import os
os.chdir(".")

hasrm = False
#clean all files with given extention in the root folder
for x in [".log","~",".pyc",".dot",".gps"]:
	for files in glob.glob("*"+x):
		os.unlink(files)
		print "removing ./"+files
		hasrm = True

#cleam pyc form tools
for files in glob.glob("tools/*.pyc"):
	os.unlink(files)
	print "removing ./"+files
	hasrm = True

#remove temp files (~) from subfolders
for root, dirnames, filenames in os.walk('.'):
	for fle in filenames:
		if(fle[len(fle)-1]=="~"):
			fname = root+"/"+fle 
			os.unlink(fname)
			print "removing ./"+fname
			hasrm = True

#clear build (files)
for root, dirs, files in os.walk("./build/"):
	path = root
	#add slash ad the end of path if needed
	if(path[len(path)-1]!="/"): path += "/"
	for x in files:
		print "removing ./"+path+x
		os.remove(path+x)
		hasrm = True

#clear build (dirs)
for root, dirs, files in os.walk("./build/"):
	path = root
	#add slash ad the end of path if needed
	if(path[len(path)-1]!="/"): path += "/"
	for x in dirs:
		print "removing ./"+path+x
		os.rmdir(path+x)
		hasrm = True

#add README file in build if not present
fname = "build/README"
if(not(os.path.isfile(fname))):
	print "adding README in ./build"
	fout = open(fname,"w")
	fout.write("this folder will contains the built files\n")
	fout.close()

if(not(hasrm)): print "nothing to clean"
print "done!"
