
!###################################################
! WARNING:This is a test auto-generated by KROME, in order to
! show a bare-minimal code to call the KROME's subroutine.
! Most of the values could not be appropriate for your
! problem, since this test is only intended as a general
! purpose example.

program test
  use krome_main !use krome (mandatory)
  use krome_user !use utility (for krome_idx_* constants and others)
  implicit none
  integer,parameter::nsp=krome_nmols !number of species (common)
  real*8::Tgas,dt,x(nsp),rho,spy,t
  
  spy = 3.65d2 * 2.4d1 * 3.6d3 !seconds per year
  
  call krome_init() !init krome (mandatory)

  call krome_set_photoBin_J21log(1d1, 1d2)

  !call krome_photoBin_scale(0d0)
  
  x(:) = 1d-20 !default abundances
  x(krome_idx_C) = .5d0
  x(krome_idx_Cj) = .5d0
  x(krome_idx_e) = krome_get_electrons(x(:))
  
  Tgas = 1.2d4 !gas temperature (K)
  dt = spy !time-step (s)

  t = 0d0
  
  do 
     dt = dt * 1.1d0
     t = t + dt
     call krome(x(:), Tgas, dt) !call KROME
     write(66,'(99E17.8)') t,x(:)
     if(t>1d6*spy) exit
  end do
  close(66)
  print *,"Test OK!"
  
end program test

